FROM node:alpine

LABEL org.label-schema.schema-version = "1.0" \
      org.label-schema.name = "FineUploader UI" \
      org.label-schema.description = "present server interface for s3handler" \
      org.label-schema.vcs-url = "" \
      org.label-schema.vendor = "ipunkt Business Solutions"